completed: false
courts:
  ca1:
    complete: true
    offset: 45332
    total: 45332
  ca10:
    complete: false
    offset: 0
    total: null
  ca11:
    complete: false
    offset: 0
    total: null
  ca2:
    complete: true
    offset: 120920
    total: 120920
  ca3:
    complete: true
    offset: 112957
    total: 112957
  ca4:
    complete: true
    offset: 187217
    total: 187217
  ca5:
    complete: true
    offset: 203460
    total: 203460
  ca6:
    complete: true
    offset: 142305
    total: 142305
  ca7:
    complete: true
    offset: 92080
    total: 92080
  ca8:
    complete: true
    offset: 103363
    total: 103363
  ca9:
    complete: false
    offset: 212809
    total: 247636
  cadc:
    complete: false
    offset: 0
    total: null
  cafc:
    complete: false
    offset: 0
    total: null
  scotus:
    complete: true
    offset: 589557
    total: 589557
schema_version: '1.0'
snapshot: '2026-06-30'
