completed: false
courts:
  ca1:
    complete: false
    offset: 20443
    total: 45332
  ca10:
    complete: false
    offset: 0
    total: null
  ca11:
    complete: false
    offset: 0
    total: null
  ca2:
    complete: false
    offset: 0
    total: null
  ca3:
    complete: false
    offset: 0
    total: null
  ca4:
    complete: false
    offset: 0
    total: null
  ca5:
    complete: false
    offset: 0
    total: null
  ca6:
    complete: false
    offset: 0
    total: null
  ca7:
    complete: false
    offset: 0
    total: null
  ca8:
    complete: false
    offset: 0
    total: null
  ca9:
    complete: false
    offset: 0
    total: null
  cadc:
    complete: false
    offset: 0
    total: null
  cafc:
    complete: false
    offset: 0
    total: null
  scotus:
    complete: true
    offset: 589557
    total: 589557
schema_version: '1.0'
snapshot: '2026-06-30'
